apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-fzwb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-fzwb
    app.kubernetes.io/part-of: my-app
  name: e2e-tests-fzwb
  namespace: qe-chuo-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-fzwb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-fzwb
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:bef37efb633b63d3e4bf872068b852de1637124fc60452cea54b2411483b2b73
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
